name: Get Commit ID

on:
  workflow_dispatch:

jobs:
  get-commit-hash:
    runs-on: [ubuntu-latest, amd64]  #runs-on: [linux] #[self-hosted, linux] # , amd64]
    steps:
      - name: Info
        run: uname -a
      - name: Clone
        uses: actions/checkout@v3
      - name: Get commit ID
        run: git rev-parse --short HEAD  # NOTE(dkorolev): This may not work from a PR-based run.
                                         # Need to test all three: Manual, open PR, push to PR.
