name: Push to GHCR

on:
  workflow_dispatch:

env:
  GHCR_USERNAME: ${{ github.actor }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}  # NOTE(dkorolev): This will not do what it should for PR-based action triggers!

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Build the container
        run: |
          echo -e 'FROM alpine:latest\nENTRYPOINT ["echo", "Commit:", "'${GIT_COMMIT:0:6}'"]' >Dockerfile
          cat Dockerfile
          docker build -t "ghcr.io/${GHCR_USERNAME}/gh-actions-commit:latest" .
      - name: Login to GHCR
        run: echo "${GHCR_PASSWORD}" | docker login ghcr.io --username "${GHCR_USERNAME}" --password-stdin
      - name: Push to GHCR
        run: |
          docker push "ghcr.io/${GHCR_USERNAME}/gh-actions-commit:latest"
          docker tag "ghcr.io/${GHCR_USERNAME}/gh-actions-commit:latest" "ghcr.io/${GHCR_USERNAME}/gh-actions-commit:${GIT_COMMIT:0:6}"
          docker push "ghcr.io/${GHCR_USERNAME}/gh-actions-commit:${GIT_COMMIT:0:6}"
